### ISSUE TITLE
Duplicate db key occurs, what should I do?

### ISSUE THREAD

**Issue by bwp618** [rakheyl/snowflake-uuid#1]
The system environment uses node fork.

Is there a way to prevent duplicate keys from occurring?

**Comment by rakheyl** [comment]
Hi!

To ensure unique IDs, each instance of the generator must have its own configuration (workerId/datacenterId) [snowflake-uuid#constructor-options](https://github.com/rakheyl/snowflake-uuid#constructor-options). If you get duplicate IDs, I assume that after the fork, several generators are operating with the same parameters.

Depending on the kind of project, it might be better to keep the generator on a dedicated process to avoid blocking the event loop, but if you want to keep a generator on each fork, you can simply give them separate IDs, something like this

```typescript
if (cluster.isPrimary) {
    for (let i = 0; i < 4; i++) {
        cluster.fork({
            WORKER_ID: i,
            DATACENTER_ID: 0,
        });
    }
} else {
    const generator = new Worker(Number(process.env.WORKER_ID), Number(process.env.DATACENTER_ID));
    console.log(generator.nextId());
}
```
